In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
Data = {'Names':['Ramesh','Suresh','Mahesh',np.nan],
       'City':['Hyd','Vizag',np.nan,'vij'],
       'Age':[np.nan,22,23,24]}
df=pd.DataFrame(Data)
df

    Names   City   Age
0  Ramesh    Hyd   NaN
1  Suresh  Vizag  22.0
2  Mahesh    NaN  23.0
3     NaN    vij  24.0

In [4]:
Data = {'Names':['Ramesh','Suresh','Mahesh',None],
       'City':['Hyd','Vizag',None,'vij'],
       'Age':[None,22,23,24]}
df=pd.DataFrame(Data)
df

    Names   City   Age
0  Ramesh    Hyd   NaN
1  Suresh  Vizag  22.0
2  Mahesh   None  23.0
3    None    vij  24.0

In [5]:
df.to_csv('data_missing.csv',index=False)

In [8]:
pd.read_csv('data_missing.csv')

    Names   City   Age
0  Ramesh    Hyd   NaN
1  Suresh  Vizag  22.0
2  Mahesh    NaN  23.0
3     NaN    vij  24.0

In [9]:
df.dtypes

Names     object
City      object
Age      float64
dtype: object

In [11]:
df.isnull()

   Names   City    Age
0  False  False   True
1  False  False  False
2  False   True  False
3   True  False  False

In [12]:
df.isnull().sum()

Names    1
City     1
Age      1
dtype: int64

**filna**

In [13]:
df.fillna(30)

    Names   City   Age
0  Ramesh    Hyd  30.0
1  Suresh  Vizag  22.0
2  Mahesh     30  23.0
3      30    vij  24.0

In [24]:
df['Age'].fillna(30)

0    30.0
1    22.0
2    23.0
3    24.0
Name: Age, dtype: float64

In [16]:
arr1 = np.array([1,2,np.nan,3])
arr2 = np.array([1,2,None,3])

In [17]:
arr1

array([ 1.,  2., nan,  3.])

In [18]:
arr2

array([1, 2, None, 3], dtype=object)

In [20]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [22]:
np.nansum(arr2)

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [26]:
df['Names'].fillna("ram")

0    Ramesh
1    Suresh
2    Mahesh
3       ram
Name: Names, dtype: object

In [30]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad')

    Names   City   Age
0  Ramesh    Hyd   NaN
1  Suresh  Vizag  22.0
2  Mahesh  Vizag  23.0
3  Mahesh    vij  24.0

In [31]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='bfill')

    Names   City   Age
0  Ramesh    Hyd  22.0
1  Suresh  Vizag  22.0
2  Mahesh    vij  23.0
3    None    vij  24.0

In [32]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='ffill')

    Names   City   Age
0  Ramesh    Hyd   NaN
1  Suresh  Vizag  22.0
2  Mahesh  Vizag  23.0
3  Mahesh    vij  24.0

In [33]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='backfill')

    Names   City   Age
0  Ramesh    Hyd  22.0
1  Suresh  Vizag  22.0
2  Mahesh    vij  23.0
3    None    vij  24.0

In [38]:
age_median = df['Age'].median()

In [35]:
df['Age'].mean()

np.float64(23.0)

In [39]:
df['Age'].fillna(age_median)

0    23.0
1    22.0
2    23.0
3    24.0
Name: Age, dtype: float64

In [40]:
df['City'].mode()

0      Hyd
1    Vizag
2      vij
Name: City, dtype: object

In [1]:
import numpy as np
from sklearn.impute import KNNImputer

In [2]:
import sklearn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
from sklearn.impute import KNNImputer

In [6]:
x = [[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]]
pd.DataFrame(x)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [11]:
imputer = KNNImputer(n_neighbors=2, weights='uniform')
imputer.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])